# Generated by Django 4.0.5 on 2022-06-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Filmes')),
                ('descriptions', models.CharField(max_length=200, verbose_name='Descrição')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
