# Generated by Django 4.0.5 on 2022-06-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_alter_movie_descriptions_alter_movie_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='descriptions',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Filmes'),
        ),
    ]
